<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeurRepository extends EntityRepository
{

    public function findSeries($id)
    {
        return $this->getEntityManager()
                        ->createQuery('SELECT s FROM AppBundle:Serie s JOIN s.roles r WHERE r.acteur = :id')->setParameter('id', $id)
                        ->getResult();
    }

}
