<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CritiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CritiqueRepository extends EntityRepository
{

    public function getCritiquesByUser($em, $id) {

        $query = $em->createQuery("SELECT c "
                    ."FROM AppBundle:Critiques c "
                    ."WHERE c.id = :id")
                    ->setParameter("id", $id);

        $critiques = $query->getResult();

        return $utilisateur;

    }

}
